### ISSUE TITLE
Does not work with Gnome 3.14

### ISSUE THREAD

**Issue by hugoroy** [gunzy83/linux-xps13-archlinux#4]
I upgraded to Gnome 3.14 this morning and now I can't seem to be able to use more than 2 fingers.

List of stuff upgraded:

[edited]

**Comment by gunzy83** [comment]
I've been having a play with Gnome 3.16 and I am yet to find a way to get Touchegg to work. Touchegg is working in Plasma 5 but Gnome appears to be intercepting the touch gestures.

I will update if I find out more.
