### ISSUE TITLE
No WiFi no ethernet

### ISSUE THREAD

**Issue by hugoroy** [gunzy83/linux-xps13-archlinux#6]
The last upgrade triggered a lot of issues for me. I can't get any WiFi or Ethernet over USB any more. I have also tried with the normal kernel in grub but problem there too... Sorry if that looks a bit vague but I'm really clueless with what's going on there. Any idea?

**Comment by gunzy83** [comment]
Like you said the problem exists in the stock kernel as well so something else must be going on other than the changes in this kernel. I would check your dmesg output for errors and check lspci and lsusb to make sure that the devices are visible to the system. If they are there is something wrong in the desktop environment or elsewhere higher in the stack (possibly a problem with a package upgrade). If you get nowhere with that, try posting to the Arch Linux BBS (more eyes on it). Good Luck

**Comment by hugoroy** [comment]
Just wanted to know if it could be anything hardware specific, since people here probably have the same.

In the end the problem was with linbm-glib and networkmanager so if anyone else experience this lately on Arch, just downgrade.
